# _config.yml

title: "AI HLS Ignited: Transforming Healthcare with Azure AI"
description: "Discover AI-powered solutions revolutionizing Healthcare & Life Sciences."
baseurl: "/ai-hsl-ignited"
url: "https://pablosalvador10.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

header:
  display_title: false
  display_description: false
  nav: false
