title: "AI HLS Ignited: Transforming Healthcare with Azure AI"
description: "Discover AI-powered solutions revolutionizing Healthcare & Life Sciences."
baseurl: "/ai-hsl-ignited"  # Ensure it matches your repository name
url: "https://pablosalvador10.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Customize appearance
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

header:
  overlay_image: "/assets/azure-banner.jpg"  # Fallback image in case video does not load
  overlay_filter: 0.5
